### ISSUE TITLE
Terrain ends abruptly and plants keep going 

### ISSUE THREAD

**Issue by BasicsCoding** [Ritsu95/3D-Game-Engine-ThinMatrix#3]
The terrain ends (i thought it was supposed to be infinite) and the plants keep rendering where there is no terrain 
![glitch 2](https://cloud.githubusercontent.com/assets/13019863/13685442/67309ff6-e708-11e5-9b93-7f97c102e214.png)

**Comment by Ritsu95** [comment]
As far as ThinMatrix has shown, the terrain isn't infinite. As regards the plant, I was too lazy to fix it xD

**Comment by Termin8or** [comment]
The terrain is fairly easy to make 'infinite', all you would need to do is add them in a for loop however you'd need to add some sort of resource manager so they're not all loaded at once, and as for the plants, thats just because if there's no terrain the physics defaults to a value of 0 for the y.
