### ISSUE TITLE
ImageIOException

### ISSUE THREAD

**Issue by Super-Admin** [Ritsu95/3D-Game-Engine-ThinMatrix#4]
I have just finished setting up the project in InteliJ Idea but when i run it it gives me an ImageIOException on line 1301 of ImageIO.java. I am sure this is set up correctly. Thanks. :8ball:
![screenshot from 2016-09-23 10-25-36](https://cloud.githubusercontent.com/assets/18099181/18781049/1c72c04c-8178-11e6-80bd-4bf6be244174.png)

**Comment by BobbyJuniorPlays** [comment]
I Don't Know Why Your Getting This Error. You Can Download The New SRC files from ThinMatrix's New Video. (The Links In The Description Of His Video). Add The RES and LIB Folders From This File To ThinMatrix's SRC And Any Additional Foldders And Launch Intellij. If This Error Continues To Persist Then Download Eclipse And Launch The Folder Because ThinMatrix Had Made The Code In Eclipse.

**Comment by JonathanOhrlingg** [comment]
This has nothing to with the ImageIO.java class. If your read the error message you can clearly see that the error comes from the Terrain class from the method generateTerrain. I would assume that it tries to load and read a height map but failes somehow. I dont use intellij but if it would have been eclipse this might be because you havn't set the resource folder (where the heightmap is located) to a class folder. This is done in eclipse by right-clicking the project -> select "Java Build Path" -> choose the tab "Libraries" -> Click "Add Class Folder" -> and then select the resource/res folder.

From the knowledge that you couldn't read this simple error i would strongly recommend you to get familiar with the java programming language before getting into advanced things like LWJGL. Start small and work you way up.
